spring:
  messages:
    basename: "i18n/appmessages"
    encoding: "UTF-8"

application:
  locale: ru_Ru
  min-correct-answers: 3
  questions-file-path: student-testing/student-testing-04/src/main/resources/questions_${application.locale}.csv
