spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL=jdbc:jdbc:postgresql://postgres:5432/db}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

logging:
  group:
    api: ${LOG_GROUP}
  level:
    api: ${LOG_LEVEL}
  file:
    file-name: ${LOG_FILE_NAME}
    total-size: ${LOG_TOTAL_SIZE_CAP}
  logback:
    rollingpolicy:
      max-file-size: ${LOG_MAX_FILE_SIZE}
      max-history: ${LOG_MAX_HISTORY}

resilience4j:
  timelimiter:
    instances:
      getAll:
        timeout-duration: ${GET_ALL_TIMEOUT_DURATION:1s}
        cancel-running-future: ${GET_ALL_CANCEL_RUNNING_FUTURE:true}
      getById:
        timeout-duration: ${GET_BY_ID_TIMEOUT_DURATION:1s}
        cancel-running-future: ${GET_BY_ID_CANCEL_RUNNING_FUTURE:true}
